### ISSUE TITLE
MS-1: Implement 1-hour user's token update

### ISSUE THREAD

**Issue by dev-alysenko** [dev-alysenko/memberships#6]
There should be used SyncAdapter that uses MemberPreferences to update current user's token

**Comment by Dwite** [comment]
why do you think 1-hour token is a good idea?

**Comment by dev-alysenko** [comment]
@Dwite Because of Firebase. It's re-generates current user's token every hour that passed. So there's only one way to retrieve new token and it's based on call Firebase API method which has return type as Task<GetResponseResult>

**Comment by dev-alysenko** [comment]
Actually, I gonna to extract authorization to the server-side to cloud functions as I've done recently for memberships creation feature. And this issue will be consider inside the server-side. But I haven't enough time for it, so I'm planning to realese this strategy

**Comment by dev-alysenko** [comment]
Implemented in the branch 'feature/memberships'
